# -*- coding: utf-8 -*-
# Generated by Django 6.0.4 on 2026-04-18 10:19
# Служебный комментарий миграции:
# Назначение: создать таблицу модели Employee при первичном применении миграций.
# Исполнитель изменения: Yemmi; дата: 02.05.2026.
# Причина изменения: пояснить автоматически созданный Django-код.
# Первоначальный фрагмент: сгенерированная миграция 0001_initial без учебных комментариев.

from django.db import migrations, models


class Migration(migrations.Migration):
    """Начальная миграция приложения employees.

    Тип: класс миграции Django.
    Формальные данные: dependencies и operations читаются миграционным раннером.
    Фактические данные: создаваемая таблица Employee и ее поля.
    Условия: миграция применяется один раз к базе данных без этой таблицы.
    Результат: структура таблицы employees_employee.
    """

    # Миграция является первой в цепочке приложения.
    initial = True

    # У первой миграции нет зависимостей от предыдущих миграций этого приложения.
    dependencies = [
    ]

    # Список операций, которые Django выполнит при применении миграции.
    operations = [
        # Операция создания модели Employee и соответствующей таблицы БД.
        migrations.CreateModel(
            name='Employee',
            fields=[
                # Первичный ключ записи сотрудника.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Фамилия сотрудника.
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                # Имя сотрудника.
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                # Отчество сотрудника, допускает пустое значение.
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                # Должность сотрудника.
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                # Адрес сотрудника.
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                # Рабочий телефон сотрудника.
                ('work_phone', models.CharField(max_length=50, verbose_name='Рабочий телефон')),
                # Личный телефон сотрудника.
                ('personal_phone', models.CharField(max_length=50, verbose_name='Личный телефон')),
            ],
            options={
                # Читаемое имя одной записи.
                'verbose_name': 'Сотрудник',
                # Читаемое имя нескольких записей.
                'verbose_name_plural': 'Сотрудники',
                # Порядок сортировки по умолчанию.
                'ordering': ('last_name', 'first_name', 'middle_name'),
            },
        ),
    ]
