# -*- coding: cp1251 -*-
"""
Django settings for firm_directory project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Корневая директория проекта, используется для построения абсолютных путей.
BASE_DIR = Path(__file__).resolve().parent.parent


# Быстрые настройки для разработки. Не использовать в production без проверки.

# Секретный ключ Django, необходим для подписи данных сессий и CSRF.
SECRET_KEY = 'django-insecure-99m(8ci@#q!19$^ck7)_%%n_op#tw8yql*0d9c5o-sc3^x_#%#'

# Включение режима отладки в процессе разработки.
DEBUG = True

# Список хостов, допустимых для обработки запросов.
ALLOWED_HOSTS = []


# Приложения Django, активированные в проекте.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employees.apps.EmployeesConfig',
]

# Список middleware, которые обрабатывают HTTP-запросы и ответы.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Корневой модуль URL-конфигурации проекта.
ROOT_URLCONF = 'firm_directory.urls'

# Настройки шаблонов Django, включая каталоги для поиска HTML-файлов.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Указывает WSGI-приложение для запуска на сервере.
WSGI_APPLICATION = 'firm_directory.wsgi.application'


# Настройки базы данных.
# Для данного проекта используется SQLite с файлом в корне проекта.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Валидация паролей, обеспечивающая безопасность пользовательских учетных записей.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Локализация и часовой пояс проекта.
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True


# Настройки статических файлов проекта.
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Параметры переадресации после аутентификации.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'employee_list'
LOGOUT_REDIRECT_URL = 'home'

# Автоматический тип поля для первичных ключей моделей по умолчанию.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
