# Generated by Django 6.0.2 on 2026-04-04 10:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='наименование группы')),
            ],
            options={
                'verbose_name': 'группа товаров',
                'verbose_name_plural': 'группы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='наименование товара')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='проданное количество')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Номинальная цена продажи за единицу до применения скидки.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='продажная цена (без скидки), за ед.')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='закупочная цена, за ед.')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Процент скидки с номинальной цены (для справки в исходных данных).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='скидка, %')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.productgroup', verbose_name='группа товара')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ['-id'],
            },
        ),
    ]
